name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Upload files to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "README.md" \
          --delete
    
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
    
    - name: Display deployment info
      run: |
        echo "🚀 Website deployed successfully!"
        echo "📍 S3 Bucket: ${{ secrets.S3_BUCKET_NAME }}"
        echo "🌐 CloudFront Distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
        echo "✅ Cache invalidated - changes should be live in a few minutes"